local M = {}

function M.open()
  local lines = {
    "┌─────────────────────────────────────────────────────────────────────────┐",
    "│                           ⌨  KEYBINDINGS                            │",
    "└─────────────────────────────────────────────────────────────────────────┘",
    "",
    "  NAVIGATION",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  h j k l              Arrow keys (wrap-aware)",
    "  w b                  Word forward/backward",
    "  0 $                  Start/end of line",
    "  gg G                 Start/end of file",
    "  Ctrl+o i             Jump back/forward",
    "  <leader>s            Flash jump",
    "  <leader>ss           Flash Treesitter",
    "  f F                  Find char forward/backward",
    "  ; ,                  Repeat find forward/backward",
    "",
    "  FILE",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>e            Toggle NvimTree",
    "  -                    Open parent (Oil)",
    "  <leader>x            Delete buffer",
    "  <leader>uf           Format buffer",
    "  <leader>ul           Lint buffer",
    "  <leader>/            Search in buffer",
    "  <leader>ff           Find files",
    "  <leader>fg           Live grep",
    "  <leader>fr           Recent files",
    "  <leader>fb           Buffers",
    "  <leader>fc           Find commands",
    "  <leader>fk           Find keymaps",
    "  <leader>fh           Help tags",
    "  <leader>fs           Treesitter symbols",
    "  <leader>fl           LSP document symbols",
    "  <leader>ft           Find TODOs",
    "",
    "  LSP",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  gD                    Go to declaration",
    "  gd                    Go to definition",
    "  K                     Hover docs",
    "  gi                    Go to implementation",
    "  <C-k>                 Signature help",
    "  <leader>ca           Code action",
    "  <leader>cr           Rename",
    "  gr                    References",
    "  [d ]d                Prev/next diagnostic",
    "  <leader>cd           Line diagnostics",
    "  <leader>dl           Diagnostic list",
    "",
    "  GIT",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>gg           LazyGit",
    "  <leader>gL           LazyGit (current file)",
    "  <leader>gd           Diff view open",
    "  <leader>gD           Diff view close",
    "  <leader>gm           Git messenger",
    "  <leader>gh           GitHub browse",
    "  <leader>gfc          Git commit",
    "  <leader>gfa          Git amend",
    "  <leader>gfp          Git push",
    "  <leader>gfu          Git pull",
    "  <leader>gfr          Git rebase",
    "  <leader>gfl          Git log",
    "  <leader>gfd          Git diff split",
    "  <leader>gfs          Git status",
    "  <leader>gcn          Choose none (conflict)",
    "  <leader>gco          Choose ours (conflict)",
    "  <leader>gct          Choose theirs (conflict)",
    "  <leader>gcb          Choose both (conflict)",
    "  <leader>gcc          Choose all (conflict)",
    "  <leader>gca          Accept current (conflict)",
    "",
    "  TROUBLE",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>xx           Diagnostics",
    "  <leader>xX           Buffer diagnostics",
    "  <leader>xs           Symbols",
    "  <leader>xl           LSP references",
    "  <leader>xq           Quickfix",
    "",
    "  DEBUG",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>dc           Continue",
    "  <leader>db           Toggle breakpoint",
    "  <leader>dsi          Step into",
    "  <leader>dss          Step over",
    "  <leader>dso          Step out",
    "  <leader>dp           Pause",
    "  <leader>dr           Open REPL",
    "  <leader>dt           Terminate",
    "  <leader>dl           Run last",
    "  <leader>dB           Conditional breakpoint",
    "  <leader>dd           DAP breakpoints (Telescope)",
    "  <leader>dv           DAP variables (Telescope)",
    "  <leader>df           DAP frames (Telescope)",
    "",
    "  FOLDS",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  zR                    Open all folds",
    "  zM                    Close all folds",
    "  zr zm                 Open/close folds except kinds",
    "  za zo zc             Toggle/open/close fold",
    "",
    "  SESSIONS",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>Se           Load session",
    "  <leader>Ss           Save session",
    "  <leader>St           Toggle session",
    "",
    "  WINDOWS",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>uz           Zen mode",
    "  <leader>ao           Aerial outline",
    "  Ctrl+\\              Toggle terminal",
    "  Ctrl+h j k l         Navigate splits",
    "  Ctrl+w < > + -       Resize splits",
    "",
    "  REFACTOR",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>rev          Extract variable (visual)",
    "  <leader>ref          Extract function (visual)",
    "  <leader>reb          Extract block (visual)",
    "  <leader>ri           Inline variable",
    "  <leader>rr           Rename variable",
    "  <leader>rdp          Debug print",
    "  <leader>rds          Debug cleanup",
    "",
    "  FLASH",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>s            Flash jump",
    "  <leader>ss           Flash Treesitter",
    "  <leader>r            Flash remote (operator)",
    "  <leader>R            Flash remote treesitter (operator)",
    "",
    "  HARPOON",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>ha           Add file",
    "  <leader>hh           Toggle menu",
    "  <leader>h1-4         Jump to file",
    "",
    "  OTHER",
    "  ──────────────────────────────────────────────────────────────────────────",
    "  <leader>up           Lazy",
    "  <leader>um           Mason",
    "  <leader>ui           Lsp Info",
    "  <leader>?            Cheatsheet",
    "  <leader>wK           WhichKey all",
    "  <leader>m            Dashboard",
    "  gc gb                Comment line/block",
    "  gcc                  Comment current line",
    "  jk                   Exit insert mode",
    "  <leader>ua           Update treesitter",
    "  <S-l>                Next buffer",
    "  <S-h>                Previous buffer",
    "  <A-j/k>              Move line down/up",
    "",
    "                                  press q or <Esc> to close",
    "",
  }

  local width = 71
  local height = #lines

  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].modifiable = false
  vim.bo[buf].filetype = "dashboard"

  local win_opts = {
    relative = "editor",
    width = width,
    height = height,
    row = math.floor((vim.o.lines - height) / 2),
    col = math.floor((vim.o.columns - width) / 2),
    style = "minimal",
    border = "rounded",
    noautocmd = true,
  }

  local win = vim.api.nvim_open_win(buf, true, win_opts)
  vim.wo[win].winhl = "Normal:Normal,FloatBorder:FloatBorder"
  vim.wo[win].cursorline = false
  vim.wo[win].foldlevel = 0

  vim.keymap.set("n", "q", function()
    vim.api.nvim_win_close(win, true)
  end, { buffer = buf, nowait = true })
  vim.keymap.set("n", "<Esc>", function()
    vim.api.nvim_win_close(win, true)
  end, { buffer = buf, nowait = true })

  return win
end

vim.api.nvim_create_user_command("Cheatsheet", function()
  M.open()
end, {})

return M

