-- Trouble.nvim configuration
require("trouble").setup({
  auto_close = true,
  auto_fold = false,
  auto_jump = false,
  auto_open = false,
  auto_preview = true,
  auto_refresh = true,
  auto_update = true,
  close_on_jump = false,
  follow = true,
  focus = false,
  indent_guides = true,
  keys = {
    ["<cr>"] = "jump",
    ["<s-cr>"] = "jump_close",
    ["o"] = "jump",
    ["<2-LeftMouse>"] = "jump",
    ["<C-e>"] = "jump_close",
    ["-"] = "fold_toggle",
    ["z"] = "fold_toggle",
    ["Z"] = "fold_close",
    ["a"] = "answer",
    ["A"] = "answer_split",
    ["e"] = "expand",
    ["E"] = "expand_all",
    ["f"] = "format",
    ["F"] = "format_all",
    ["c"] = "close",
    ["C"] = "close_all",
    ["p"] = "preview",
    ["P"] = "preview_external",
    ["r"] = "refresh",
    ["R"] = "refresh_all",
    ["j"] = "next",
    ["k"] = "prev",
    ["J"] = "last",
    ["K"] = "first",
    ["O"] = "open",
    ["S"] = "open_split",
    ["s"] = "open_vsplit",
    ["t"] = "open_tab",
  },
  mode = "diagnostics",
  pinned = false,
  preview = {
    border = "single",
    mapping = {
      ["<cr>"] = "jump",
      ["o"] = "jump",
      ["<2-LeftMouse>"] = "jump",
      ["<C-e>"] = "jump_close",
    },
  },
  reverse = false,
  save_last_folds = true,
  scroll = {
    default = 5,
    jump = true,
    padding = 4,
  },
  search = {
    highlight = true,
    mapping = {
      ["/"] = "search",
      ["n"] = "next",
      ["N"] = "prev",
    },
  },
  severity = {
    min = vim.diagnostic.severity.ERROR,
    max = vim.diagnostic.severity.HINT,
  },
  sort = {
    by = "severity",
    dir = "asc",
  },
  split = "right",
  title = "Diagnostics",
  type = "list",
  update = {
    event = {
      "BufWritePost",
      "CursorHold",
      "CursorHoldI",
      "BufReadPost",
    },
    throttle = 100,
  },
})
