require("which-key").setup({
  trigger = "auto",
  timeout = 300,
  plugins = {
    marks = true,
    registers = true,
    spelling = true,
    presets = {
      operators = true,
      motions = true,
      text_objects = true,
      windows = true,
      nav = true,
      z = true,
      g = true,
    },
  },
  icons = {
    group = "+",
  },
})

vim.defer_fn(function()
  require("which-key").add({
    { "<leader>a",   desc = "Aerial Outline" },
    { "<leader>c",   group = "Code" },
    { "<leader>ca",  desc = "Code action" },
    { "<leader>cd",  desc = "Diagnostics" },
    { "<leader>cr",  desc = "Rename" },
    { "<leader>d",   group = "Debug" },
    { "<leader>db",  desc = "Toggle breakpoint" },
    { "<leader>dc",  desc = "Continue" },
    { "<leader>dd",  desc = "DAP breakpoints" },
    { "<leader>df",  desc = "DAP frames" },
    { "<leader>di",  desc = "Step into" },
    { "<leader>do",  desc = "Step over" },
    { "<leader>dr",  desc = "Open REPL" },
    { "<leader>du",  desc = "Step out" },
    { "<leader>dv",  desc = "DAP variables" },
    { "<leader>f",   group = "Find/File" },
    { "<leader>fb",  desc = "Find buffers" },
    { "<leader>fc",  desc = "Find commands" },
    { "<leader>ff",  desc = "Find files" },
    { "<leader>fg",  desc = "Live grep" },
    { "<leader>fh",  desc = "Help tags" },
    { "<leader>fk",  desc = "Find keymaps" },
    { "<leader>fl",  desc = "LSP symbols" },
    { "<leader>fr",  desc = "Recent files" },
    { "<leader>fs",  desc = "Treesitter symbols" },
    { "<leader>ft",  desc = "Find TODOs" },
    { "<leader>g",   group = "Git" },
    { "<leader>gB",  desc = "Git browse" },
    { "<leader>gD",  desc = "Close diff view" },
    { "<leader>gL",  desc = "LazyGit current file" },
    { "<leader>gd",  desc = "Open diff view" },
    { "<leader>gg",  desc = "LazyGit" },
    { "<leader>gm",  desc = "Git messenger" },
    { "<leader>gc",  group = "Conflict" },
    { "<leader>gcb", desc = "Choose both" },
    { "<leader>gcn", desc = "Choose none" },
    { "<leader>gco", desc = "Choose ours" },
    { "<leader>gct", desc = "Choose theirs" },
    { "<leader>h",   group = "Harpoon" },
    { "<leader>ha",  desc = "Add file" },
    { "<leader>hh",  desc = "Toggle menu" },
    { "<leader>h1",  desc = "Jump to 1" },
    { "<leader>h2",  desc = "Jump to 2" },
    { "<leader>h3",  desc = "Jump to 3" },
    { "<leader>h4",  desc = "Jump to 4" },
    { "<leader>m",   desc = "Dashboard" },
    { "<leader>r",   group = "Refactor" },
    { "<leader>s",   desc = "Flash jump" },
    { "<leader>ss",  desc = "Flash Treesitter" },
    { "<leader>S",   group = "Session" },
    { "<leader>Se",  desc = "Load session" },
    { "<leader>Ss",  desc = "Save session" },
    { "<leader>St",  desc = "Toggle session" },
    { "<leader>u",   group = "UI" },
    { "<leader>ua",  desc = "TS update" },
    { "<leader>ue",  desc = "Toggle Edgy" },
    { "<leader>uf",  desc = "Format buffer" },
    { "<leader>ui",  desc = "LSP info" },
    { "<leader>ul",  desc = "Lint buffer" },
    { "<leader>um",  desc = "Mason" },
    { "<leader>up",  desc = "Lazy" },
    { "<leader>uz",  desc = "Zen mode" },
    { "<leader>w",   group = "Work/Window" },
    { "<leader>wa",  desc = "Task action" },
    { "<leader>wq",  desc = "Quick action" },
    { "<leader>wr",  desc = "Run task" },
    { "<leader>wt",  desc = "Toggle task" },
    { "<leader>wK",  desc = "WhichKey all" },
    { "<leader>x",   group = "Trouble" },
    { "<leader>xL",  desc = "LSP references" },
    { "<leader>xq",  desc = "Quickfix" },
    { "<leader>xs",  desc = "Symbols" },
    { "<leader>xx",  desc = "Diagnostics" },
    { "<leader>xX",  desc = "Buffer diagnostics" },
    { "<leader>?",   desc = "Cheatsheet" },
    { "<leader>/",   desc = "Search buffer" },
    { "<leader>-",   desc = "Oil parent dir" },
  })
end, 500)
